'use client'

import { createContext, useEffect, useState } from 'react'
import './globals.css'

// Causing an error
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

interface AuthContextProps {
  user: object
  setUser: React.Dispatch<React.SetStateAction<string>>
}

export const AuthContext = createContext<AuthContextProps>({
  user: {
    user: {},
    token: '',
  },
  setUser: () => {},
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [user, setUser] = useState({})

  useEffect(() => {
    const localUser = localStorage.getItem('auth')
    let auth

    if (localUser) {
      auth = JSON.parse(localUser)
    }

    if (auth?.user && auth?.token) {
      setUser(auth)
    }

    if (user) return
  }, [])
  return (
    <AuthContext.Provider value={{ user, setUser }}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthContext.Provider>
  )
}
