'use client'

import { createContext, useEffect, useState } from 'react'
import './globals.css'

// Causing an error
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
        <head>
          <title>Manga DB</title>
        </head>
        <body>{children}</body>
      </html>
  )
}
